CardTest/Models/DeviceListItem.cs
using CardTest.Data;
using System;
using System.Collections.Generic;

namespace CardTest.Models
{
	public class DeviceListItem
	{
		private Dictionary<NMTState, string> markClasses = new Dictionary<NMTState, string>
		{
			{ NMTState.BootUp, "info" },
			{ NMTState.PreOperational, "warning" },
			{ NMTState.Operatuional, "success" },
			{ NMTState.Stopped, "danger" },
			{ NMTState.Unknown, "secondary" },
		};

		public byte NodeID { get; set; }
		public NMTState NMTState { get; set; }

		public UniqueLSSId LSSId { get; set; }

		public TimeSpan TimeFromLastHeartbeat { get; set; }

		/*
		public DeviceState StateMonitor { get; set; }

		public int DeviceType { get; set; }

		public string VendorName { get; set; }
		public string DeviceName { get; set; }
		public bool IsEdsLoaded { get; set; }
		public int TPDOConfigured { get; set; }
		*/

		public string MarkClass => markClasses[NMTState];

		public string NMTStateString => NMTState.GetDescription();

		public string HeartBitIconColor
		{
			get
			{
				if (TimeFromLastHeartbeat < TimeSpan.FromSeconds(1))
				{
					return "success";
				}
				else if (TimeFromLastHeartbeat < TimeSpan.FromSeconds(5))
				{
					return "warning";
				}
				else
				{
					return "danger";
				}
			}
		}

		public string VendorString { get; set; }
		public string ProductString { get; set; }

		public bool IsBootloader { get; set; }

		public bool EdsLoaded { get; set; }

		public string HeartbeatText
		{
			get
			{
				if (TimeFromLastHeartbeat < TimeSpan.FromSeconds(1))
				{
					return "Менее секунды назад";
				}
				else if (TimeFromLastHeartbeat < TimeSpan.FromSeconds(5))
				{
					return $"{TimeFromLastHeartbeat:s\\.f} секунд назад";
				}
				else
				{
					return $"{TimeFromLastHeartbeat} секунд назад";
				}
			}
		}
	}
}

CardTest/ViewComponents/DeviceCard/DeviceCardBodyViewComponent.cs
using CardTest.Models.DeviceCardModels;
using Microsoft.AspNetCore.Mvc;

namespace CardTest.ViewComponents
{
	public class DeviceCardBodyViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke(string MarkClass, string Vendor, string Product,
			uint Revision, uint Serial, bool EdsReload)
		{
			return View(new DeviceCardBodyModel
			{
				MarkClass = MarkClass,
				Vendor = Vendor,
				Product = Product,
				Revision = Revision,
				Serial = Serial,
				EDSButtonTooltip = (EdsReload ? "Изменить" : "Загрузить") + " EDS"
			});
		}
	}
}

CardTest/ViewComponents/DeviceCard/DeviceCardBootloaderFooterViewComponent.cs
using CardTest.Models.DeviceCardModels;
using Microsoft.AspNetCore.Mvc;

namespace CardTest.ViewComponents
{
	public class DeviceCardBootloaderFooterViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke(byte NodeID, uint AppID)
		{
			return View(new DeviceCardBootloaderFooterModel
			{
				NodeID = NodeID,
				AppID = $"0x{AppID:X8}"
			});
		}
	}
}

CardTest/ViewComponents/DeviceCard/DeviceCardHeaderViewComponent.cs
using CardTest.Data;
using CardTest.Models.DeviceCardModels;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CardTest.ViewComponents
{
	public class DeviceCardHeaderViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke(string MarkClass, byte NodeID, NMTState NmtState, TimeSpan Heartbeat, bool AvatarReady)
		{
			var model = new DeviceCardHeaderModel
			{
				MarkClass = MarkClass,
				NodeID = NodeID,
				NmtStateString = NmtState.GetDescription(),
				AvatarIcon = AvatarReady ? "map-marker-alt" : "question"
			};

			if (Heartbeat < TimeSpan.FromSeconds(1))
			{
				model.HeartbeatToolTip = "Менее секунды назад";
				model.HeartBitIconColor = "success";
			}
			else if (Heartbeat < TimeSpan.FromSeconds(5))
			{
				model.HeartbeatToolTip = $"{Heartbeat:s\\.f} секунд назад";
				model.HeartBitIconColor = "warning";
			}
			else
			{
				model.HeartbeatToolTip = $"{Heartbeat} секунд назад";
				model.HeartBitIconColor = "danger";
			}

			return View(model);
		}
	}
}

CardTest/ViewComponents/DeviceCard/DeviceCardTpdoSummaryFooterViewComponent.cs
using CardTest.Models.DeviceCardModels;
using Microsoft.AspNetCore.Mvc;

namespace CardTest.ViewComponents
{
	public class DeviceCardTpdoSummaryFooterViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View(new DeviceCardTpdoSummaryFooterModel());
		}
	}
}

CardTest/Views/Home/Components/DeviceListItem/Default.cshtml
@model DeviceListItem

<div class="card border-@Model.MarkClass" node-id="@Model.NodeID">
    <vc:device-card-header mark-class="@Model.MarkClass" node-id="@Model.NodeID"
                           nmt-state="@Model.NMTState" heartbeat="@Model.TimeFromLastHeartbeat"
                           avatar-ready="@Model.EdsLoaded" />

    <vc:device-card-body mark-class="@Model.MarkClass" vendor="@Model.VendorString" product="@Model.ProductString"
                         revision="@Model.LSSId.RevisionNumber" serial="@Model.LSSId.SerialNumber"
                         eds-reload="@Model.EdsLoaded" />

    <div class="card-footer bg-transparent border-@Model.MarkClass">
        @if (Model.IsBootloader)
        {
            <vc:device-card-bootloader-footer node-id="@Model.NodeID" app-id="0x12345678"/>
        }
        else
        {
            @if (Model.NMTState == CardTest.Data.NMTState.Operatuional)
            {
                <vc:device-card-tpdo-summary-footer />
            }
            else
            {
                <p class="card-text text-secondary text-center">
                    <i>Для работы TPO необходимо <a href="javascript:NMTTarget(@Model.NodeID, 'start');">включить</a> устройство</i>
                </p>
            }
        }
    </div>
</div>